import type { Metadata } from "next";
import RootFont from "./components/RootFont";
import "./globals.css";

export const metadata: Metadata = {
  // icon: '/user_key_zhuge.png',
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RootFont />
        {children}
      </body>
    </html>
  );
}
